driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.5
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[firefox_test::default]
      - recipe[firefox_test::version]
      - recipe[firefox_test::x11]

  - name: custom_version
    run_list:
      - recipe[firefox_test::default]
    attributes: { firefox: { version: "28.0+build2-0ubuntu2" } }
    includes:
      - ubuntu-14.04
