driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.7
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: windows-8.1
    driver_config:
      box: chef/windows-8.1-professional
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private box in Chef's Atlas account
      provider: vmware_fusion

suites:
  - name: default
    run_list:
      - recipe[firefox_test::default]
  - name: custom_version
    run_list:
      - recipe[firefox_test::default]
    attributes: { firefox: { version: "28.0+build2-0ubuntu2" } }
    includes:
      - ubuntu-14.04
